language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint --root src/bundles/ --input polylint.html
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default' --skip-plugin local --plugin sauce;
  fi
env:
  global:
  - secure: kVJfuiFWFHKfXwBTIzOzrqi9IrstjbAlhhIFhJnk85DO6v7VsLmiRXAyXvC0/uftqT5RGVf3RaB4EoewDRY4dx/x7LyjLla5gBAJax1dZOF3Et6d1iw6Lv7qoTQdPo7bndP8OBvqcdF20ECWf2dBUSHUjIHxwuHmKby8++jniODXmcKKLs9HjLthLkvpLtCrNE+kD69NzJxWHAYDBsT89udLW6uNGjk/I2sumxzH7sev9XYLfD+wPjEG6Lifg2tyjFrlC/220eFK7jq2H3H5msj6J5kU5XR4XzY00aOyVSd7dpJjsoC2H7mKpcgq5ddSf7C6b07HL116WHbI1qJJtXlfoYSJz6kPbLEa8mPacjh5YvVCvOpuiqv7zkY8JKYEzpelGnpBtwaDZnOBioo3QTKrYECZScJn01At9X/fueMEIKxaKrwbR4dYkxidO8MNJO1nhUH6v45EOop91pUAHjxNCleJBZO2xA3JTb+O26rl2k0ZkZkt/nGqg5SGv+n3eZvKSaRaIb7UsHVnKtH3XbRgV2OoSE14wwmj2zs4T71jjS2RIggXiXPuWULmbputxn1bRs6vTBAwLTchN6959KoN9aTiSQuiDrCevUL2TerHjlRV1OjHDaHwZiVcS1EzT5wyV1wHX3/Zsc6VJ3md1d9Zirrrd9RWcafka3RhOjk=
  - secure: exEyfpncMtMFAs7xpYMWJCayNOMzKk4/z23fYmFEZXx5TP8zj8k5QlxB7KibjNFrI3uec+kmN3kVwoc6kPFXPJmMavEpG7HLC1hJ+vgQjVi0omKlWPOVXZ4Yi+vFtS8uQLzCeitTpnllizDjdt3ZDBEm5UnUC81WlLTBZ4i+IaVp3+TDPTgghjB7w7iyna/ak0+ysK+rd7mHYxqVUMY3En7zbLnEhGs286ebWbHYgF0woziXxIh4ZofFxW795tjh41txCMzozzZ0ZqyyaL5w0h/fo6N34vnLqCS2sO9uVQpZNEKH2j+X2m+5PWwz2LvB3meYfQ4vxXwee/AhQyfHgxPjogk1lNtymNmYYSd5Xicl8i4oZjvnv4Y/NxkCJktIvF0WgNrSQKhy0HVCXg2p1dVUcuK6gMamJVsL6Q+UA1LodZ0FUt0ZlV2DIl67dOyMVTrt8aHY9Rrg6+bciUid20k0orFxK8LSUb1tuO1NGaMdlNOamzmlT8PbtvXiwdw/XpISfBZua89pmMu4sabF6E0Yjr/muEmrbYGBDng/F8mPlE7TiVg3O/6QliA8+rlia+j+/kRfPeVAmvjD1YYV7R5OYl92kDIYMIZjQXeaV9w9ODkp7zYqTAc8woIOBhwT34oAvjrWebkdiERYOL+Xl8nC5WPYywu1nmhmsqfLFVM=
