language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint --root app/
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default' --skip-plugin local;
  fi
env:
  global:
  - secure: DiQgONoOJlZ2SxOCI6waDLBDyE9gvErEg4vXJ6QD+KG8EDzw9PtOQ5mFYC8s+Wu9BmD8h2NrR3BDxVaoC7o1GIpVDuFHfamouAGa28d+ry7sHl+KwdcMrhrL9yYFIhhbrMWrZO+wuPfgMLtZPbcvUBuj7PQLbGf8Z/XZlsG/9R6+Y29RaL6sft8BvVyIlz3IDZxOY0+IRdTV97RVZqgClpR5RcbU5o2gDWCLrT44vFbaxbdrc46cYZF2n7DPpBRdlSWC3HcKUG/Zoiu2OxAfd54MyNfMDfcuMQ4KHjnOpZTS51RWYPg9B2z8FMY44A9z9MwergstKHhDISKVs3VbaxI0x9n8bCVplcvqwY0+gTj/5Kg0PCdMQr/gi4kIVQRShkN0RMvTiMtmrZQd6JRS0N5HLZzju8lOWvmovMlbztIh8jo7S9xhX6pVBKvxvCs1RcJmUH6ZhZLv+lNWlziY6bl14Jg9xDl3jxkLzp2P5wWj1VzdKIZIj1YNBWioQHLCvEmjDeajgwTHTg02R+MfmPTwl88VeJgqH3H0FHyR/Drtebympom7iICz8Fw7kxKCm6sLzi6x/LL58thpOyhvUjvHFlpv/m4boaXgEWEwiqCdzrm5XxZc3mPB7LLF70ttCx0O+TeQyEAlvqsaM/AT4K86T3hrIn5fPnBcMGkkc9A=
  - secure: lLyyLYPnKKy6rhQrFaMXYur99rwn4wFQYBcfAjnTPEhJEzJ/N5C/Lgba4gsLDDliAb6IF30xq1vgOOHt/Y+QEOvos0KfBkiPVJjosegy4vtInfYKwSl42MPedV3NHGanuGdl/+E47HWZL1/6nK+FAAlPUPyQZixRXN3l7q2WawdkHJTkfHmAfypOiPigcPJ9cOELViXcejLWp6lcPHsN20SWkKVlBhA8/R29PDfrFdhHqkYJG+egSuSc5Xdepueei6KbAeqK6eDtuCJazlq/zqW2r94eoT4XDDOFY0M8llrF6ohYJ71oCa5c7rJ5SZ6CGnL6MQEHG6KST6+o9+yjnO5brGGWa9WkeBzmnD2zicUkngKnVWTB8Nl7gi6qp4K3iKPZ5LhGhCClbxM38lgm8f4S70Y2rGZocd9bzxEUjaecIId2u/R9SpT4Gh4W8f7i8IMiHsCr1viJqHzjgiyH971ZWntejoJhYZRvv5EAsZ5Gsj/RXL59sJmh7V4rmaIAlyBBbfyc8yhFX67w0eWaHT4y6r9EH45w8drcU+1PzI232jU/c/jG6p3lt/FdArV38P2vRe9BlSZhy6k22IXT1Ei8UeCH9f5WZ9FSf/Tcr/XKldWRn7HOKYBeEMi7+8jA0JINer/640v5/tNvxgY206BQ233X1uaNxIBr2SHYWaE=
